# NumPy Data Explorer
A beginner-friendly project demonstrating NumPy basics.

## 1. Import Libraries

In [1]:
import numpy as np
import time

## 2. Array Creation

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(10)
arr3 = np.linspace(0, 1, 5)
arr1, arr2, arr3

(array([1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

## 3. Indexing and Slicing

In [3]:
arr = np.arange(20)
first_five = arr[:5]
middle = arr[5:15]
last_three = arr[-3:]
first_five, middle, last_three

(array([0, 1, 2, 3, 4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 array([17, 18, 19]))

## 4. Mathematical & Statistical Operations

In [4]:
data = np.random.randint(1, 100, size=10)
sum_val = np.sum(data)
mean_val = np.mean(data)
min_val = np.min(data)
max_val = np.max(data)
sum_val, mean_val, min_val, max_val

(np.int64(621), np.float64(62.1), np.int64(18), np.int64(89))

## 5. Reshaping and Broadcasting

In [5]:
mat = np.arange(12).reshape(3, 4)
broadcast_result = mat + 5
mat, broadcast_result

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]))

## 6. Save and Load NumPy Arrays

In [6]:
np.save('saved_array.npy', arr1)
loaded = np.load('saved_array.npy')
loaded

array([1, 2, 3, 4, 5])

## 7. NumPy vs Python List Performance

In [7]:
size = 1_000_000
py_list = list(range(size))
np_arr = np.arange(size)

start = time.time()
py_result = [x*2 for x in py_list]
py_time = time.time() - start

start = time.time()
np_result = np_arr * 2
np_time = time.time() - start

py_time, np_time

(0.0772242546081543, 0.005322456359863281)